---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver:
      box: chef/ubuntu-12.04
      box_url: http://build.ticketfly.com/artifactory/uploaded-binaries/chef/boxes/opscode_ubuntu-12.04_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[tfly-artifactory::default]
    attributes:
